### ISSUE TITLE
Choose unit Format

### ISSUE THREAD

**Issue by ovhelemann** [neopsis/niagara-weather#1]
Hi there,

First of all, I just registered to GitHub, so please do not blame me, if I do something wrong here. But I think I should use "Issues" for that point.

I have seen you hardcoded the unit-format into imperial. I think it would be nice to choose between metric and imperial. 

Is it possible for a future release? Thanks so far!
ovhelemann

https://github.com/neopsis/niagara-weather/blob/ebb71decd73401590619b03c7de1e651dfa06f3f/envasWeather-rt/src/main/java/com/neopsis/envas/weather/openweathermap/NvOwmReader.java#L53

**Comment by ovhelemann** [comment]
I just read:
https://github.com/neopsis/niagara-weather/blob/ebb71decd73401590619b03c7de1e651dfa06f3f/envasWeather-rt/src/main/java/com/neopsis/envas/weather/openweathermap/NvOwmReader.java#L43

So this means I use the unitConvert Component for that or should niagara make it itself somehow?
regards!

**Comment by dapcontrols** [comment]
Hi,
UnitConvert is ok or you can change your workbench unit in metric but I don't recommend dependently your location.

**Comment by dams74** [comment]
I have a problem with unit.
How can i choose °C unit?
Thks for your help.
Damien
Edit: To do this metric unit must be choose in user service

**Comment by envas** [comment]
The values are always retrieved from the service with imperial units. You have to change the unit conversion in your workbench (for Px views) and/or in your user profile (for Hx/HTML view). 

<img width="784" alt="WeatherReport - metric units" src="https://user-images.githubusercontent.com/25388570/72606108-47863000-391e-11ea-8cee-5c11d0f2e9d8.png">

**Comment by dams74** [comment]
And if you want the weather in french, edit the weather lexicon or download this file, delete '.txt" and put it in the lexicon folder.
[weather.lexicon.txt](https://github.com/neopsis/niagara-weather/files/4076723/weather.lexicon.txt)

**Comment by envas** [comment]
The module `niagara-weather` (e.g. `envasWeather-rt`) is only a runtime module providing the communication with the weather data provider, in this case, the `Openweather`. It's the plugin into the Tridium `WeatherService`.  All language-specific tasks must be implemented in the `weather-wb` module lexicon. 

@dams74 : thank you for contribution.
