### ISSUE TITLE
Unable to configure

### ISSUE THREAD

**Issue by lprose** [neopsis/niagara-weather#3]
Hi,
I am using EC-Net 4 from Distech.
I was able to select the new provider (Open Weather Map Service), but when trying to configure it, I'm unable to write in the fields (Location, Api Key, Fault Cause).
Everything I type is not showing in the fields.

Any idea?
![Capture](https://user-images.githubusercontent.com/54711853/64021677-83049700-cb02-11e9-8cb4-9e2151bb28ae.JPG)

**Comment by scrambledleek** [comment]
I found they could be filled in by viewing the AX Property Sheet for the Provider (using Vykon Workplace ,but it should work the same).

**Comment by dams74** [comment]
Hi 
I using IQVISION from Trend Controls niagara 4.7
I have the same problem, it's impossible for me to enter location and Api Key.
How can i do this?

Edit: After restart the station, it's ok.

**Comment by envas** [comment]
It's a bug in Niagara Framework's `Weather Service`. You have to

* Add the modules `weather-rt`, `weather-wb` and `envasWeather-rt`  to your modules
* reboot the station!
* open the `WeatherReport - Property Sheet` and edit the `Location` and `Api Key` properties
